# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  api.tool_normalizer:
      class: ApiBundle\Service\Normalize\ToolNormalizer
  api.tool_handler:
    class: ApiBundle\Service\Request\ToolHandler
    arguments: ["@doctrine.orm.entity_manager"]



